feat(23.10): add grep slice
canonical/chisel-releases pull request #117
Opened 2024-02-02 15:34 UTC by lwnexgen

Add `grep` slice for Ubuntu 23.10.

Supports running `grep`, `egrep`, etc.

2024-02-06 16:21 UTC, cjdcordeiro requested changes
thanks! also missing `libpcre3` here

2024-02-06 16:21 UTC, cjdcordeiro commented on slices/grep.yaml
> +  deprecated:
```suggestion

  deprecated:
```

2024-02-07 08:08 UTC, cjdcordeiro requested changes
Sorry, I didn't mean `libpcre3` was missing from the `deprecated` slice, but rather it is missing from the `ubuntu-23.10` release. So if you try to install your slices, it won't work.

But as @rebornplusplus mentioned in https://github.com/canonical/chisel-releases/pull/118#discussion_r1480906803, in 23.10, `grep` depends on libpcre2-8-0 and not libpcre3 (and the former already exists in this chisel ubuntu release)

2024-02-07 17:25 UTC, lwnexgen commented
> But as @rebornplusplus mentioned in https://github.com/canonical/chisel-releases/pull/118#discussion_r1480906803, in 23.10, grep depends on libpcre2-8-0 and not libpcre3 (and the former already exists in this chisel ubuntu release)

Whoops, good catch - will resolve and actually test this time.

2024-02-07 17:31 UTC, cjdcordeiro approved these changes
thanks! lgtm

2024-02-09 05:33 UTC, rebornplusplus approved these changes
Looks good to me.

2024-02-09 05:34 UTC, merged