feat(23.10): add archive for curl and its dependencies
canonical/chisel-releases pull request #127
Opened 2024-02-09 12:32 UTC by yashashwi

2024-02-20 05:52 UTC, yashashwi commented
@cjdcordeiro gentle review reminder!

2024-02-20 11:13 UTC, yashashwi commented
@cjdcordeiro  Do you see a point in a tool like this?

![image](https://github.com/canonical/chisel-releases/assets/15886978/7090690e-bac6-4d69-86ae-648c8585d591)

2024-02-21 14:46 UTC, cjdcordeiro commented
> @cjdcordeiro Do you see a point in a tool like this?
> 
> ![image](https://private-user-images.githubusercontent.com/15886978/306239968-7090690e-bac6-4d69-86ae-648c8585d591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjY3NzIsIm5iZiI6MTcwODUyNjQ3MiwicGF0aCI6Ii8xNTg4Njk3OC8zMDYyMzk5NjgtNzA5MDY5MGUtYmFjNi00ZDY5LTg2YWUtNjQ4Yzg1ODVkNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE0NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkODI4YmU5OTU5YjEwNDJiY2ZkNTNmNzg2NjlkYmExMGQyZWE5ZmU0MmI5ZGI2YTU5NTM5MjQ1NDRkOTc3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hX30eAyQhzzgGy4tzl9tBmrsmGG41gbsBhsL1rGatRQ)

this is interesting @yashashwi :)

We'll be working, in the future, on expanding chisel to have additional tooling to help both the inspection and creation of slices. The slice inspection and discoverability features are already being proposed in https://github.com/canonical/chisel/pull/99 and https://github.com/canonical/chisel/pull/101.

The assisted creation of slices shall come later, but it is extremely refreshing to see the community coming up with their own solutions :)

2024-02-21 15:03 UTC, cjdcordeiro requested changes
Thanks for the PR!

Just a few nitpicks and a leftover SDF to fix

2024-02-21 15:03 UTC, cjdcordeiro commented on slices/libssh2-1.yaml
> +      /usr/lib/*-linux-*/libssh2.so*:
```suggestion
      /usr/lib/*-linux-*/libssh2.so.1*:
```

2024-02-22 08:31 UTC, yashashwi commented on slices/libldap-2.5-0.yaml
removed

2024-02-22 08:37 UTC, yashashwi commented
@cjdcordeiro  Fixed review comments.

2024-02-26 10:16 UTC, yashashwi commented
@cjdcordeiro  review pending.

2024-02-27 11:44 UTC, yashashwi commented
@rebornplusplus  could you please review this.

2024-02-28 06:46 UTC, rebornplusplus requested changes
Only one dependency seems to be wrong. Everything else looks very good. Thank you!

2024-02-28 06:46 UTC, rebornplusplus commented on slices/libssh2-1.yaml
> +      - libgcrypt20_libs
```suggestion
      - libssl3_libs
```

2024-02-28 08:53 UTC, rebornplusplus approved these changes
LGTM, thank you!

2024-03-01 07:34 UTC, yashashwi commented
@cjdcordeiro  review pending.

2024-03-06 15:24 UTC, cjdcordeiro commented
Hi @yashashwi 

apologies for the delay but we've been working on some high priority CI checks that are a must for all the pending PRs.
In the meantime, I've re-run the CLA check and it is still failing. It appears there are multiple authors in your commits, including a local user

2024-03-06 15:24 UTC, cjdcordeiro requested changes
failing CLA check

2024-03-06 15:36 UTC, yashashwi commented
> failing CLA check

Yeah some of the initial commits have been as the root user. It seems I have to recommit all of it and re raise the PR.

Np! I understand you are occupied.

2024-03-11 07:22 UTC, closed without merging

2024-03-11 07:22 UTC, linostar commented
Closed in favor of #186