bug(24.04): make /var/run a symlink to /run
canonical/chisel-releases pull request #130
Opened 2024-02-12 16:00 UTC by lwnexgen

On full Ubuntu VMs/hardware installs, as well as the upstream Ubuntu containers, /var/run is a symlink to /run. Chiseled containers do not make this symlink - this causes issues with Docker Swarm installs (and probably other projects), which mount secrets into /run.

2024-02-13 11:17 UTC, rebornplusplus approved these changes

2024-02-14 08:27 UTC, cjdcordeiro requested changes

2024-02-14 08:27 UTC, cjdcordeiro commented on slices/base-files.yaml
> +      # on full Ubuntu installs and containers
```suggestion
      # The /var/run symlink is enforced by the package's maintainer scripts
```

2024-02-14 14:35 UTC, cjdcordeiro approved these changes
LGTM, thanks @lwnexgen 

Can you please apply the same changes to the remaining PRs?

2024-02-14 14:36 UTC, merged