feat(24.04): add slices for Python 3.12
canonical/chisel-releases pull request #135
Opened 2024-02-18 04:46 UTC by lengau

Based heavily on the Python 3.11 package, but adding several new files and removing deprecated ones.

2024-02-19 07:15 UTC, rebornplusplus commented
Wow, nice. I didn't expect that all the dependencies of python3.12 would already be sliced. I will take a look shortly, thanks!

2024-02-21 16:43 UTC, cjdcordeiro requested changes
noice!! TY

The pkg seems to have changed a bit. My suggestions will make the installation succeed, but I recommend, on a 2nd pass, that we do a diff between the contents listed here and the actual debs' contents, and see if there are any paths missing from these slice definitions

2024-02-21 16:43 UTC, cjdcordeiro commented on slices/libpython3.12-minimal.yaml
> +      /usr/lib/python3.12/lib-dynload/_ssl.cpython-311-*-linux-*.so:
```suggestion
      /usr/lib/python3.12/lib-dynload/_hashlib.cpython-312-*-linux-*.so:
      /usr/lib/python3.12/lib-dynload/_ssl.cpython-312-*-linux-*.so:
```

2024-02-21 16:43 UTC, cjdcordeiro commented on slices/libpython3.12-minimal.yaml
> +      /usr/lib/python3.12/zipfile.py:
```suggestion
      /usr/lib/python3.12/zipfile/**:
```

2024-02-21 16:43 UTC, cjdcordeiro commented on slices/libpython3.12-stdlib.yaml
> +      - libcrypt1_libs
it will need this fix https://github.com/canonical/chisel-releases/pull/138

2024-02-21 16:43 UTC, cjdcordeiro commented on slices/libpython3.12-stdlib.yaml
> +  # https://docs.python.org/3.11/library/unix.html
```suggestion
  # https://docs.python.org/3.12/library/unix.html
```

there are still a few references to python3.11. Could you pls double check for others

2024-02-21 16:43 UTC, cjdcordeiro commented on slices/libpython3.12-stdlib.yaml
> +      /usr/lib/python3.12/_bootsubprocess.py:
```suggestion
```

2024-02-21 16:43 UTC, cjdcordeiro commented on slices/libpython3.12-stdlib.yaml
> +      /usr/lib/python3.12/lib-dynload/_typing.cpython-312-*-linux-*.so:
```suggestion
```

2024-02-21 16:43 UTC, cjdcordeiro commented on slices/libpython3.12-stdlib.yaml
> +      /usr/lib/python3.12/smtpd.py:
```suggestion
```

it's in /usr/lib/python3.12/test/support/smtpd.py now

2024-05-16 07:25 UTC, closed without merging