feat(24.04): add apt and dependencies
canonical/chisel-releases pull request #136
Opened 2024-02-18 06:13 UTC by lengau

2024-02-21 17:14 UTC, cjdcordeiro requested changes
Tyvm! Some interesting stuff here.

We'll probably need to have a deeper look at the slices design, since some of these packages (like `apt`) offer multiple functionalities

2024-02-21 17:14 UTC, cjdcordeiro commented on slices/dpkg.yaml
> +      - libzstd1
```suggestion
      - libzstd1_libs
```

2024-02-21 17:14 UTC, cjdcordeiro commented on slices/libsystemd0.yaml
> +      - liblz4_libs
```suggestion
      - liblz4-1_libs
```

2024-02-21 17:14 UTC, cjdcordeiro commented on slices/libapt-pkg6.0.yaml
> +      - liblz4_libs
```suggestion
      - liblz4-1_libs
```

2024-02-21 17:14 UTC, cjdcordeiro commented on slices/apt.yaml
> +      - libapt-pkg.so.6.0_libs
```suggestion
      - libapt-pkg6.0_libs
```

2024-02-21 17:14 UTC, cjdcordeiro commented on slices/libcap2.yaml
> +      /usr/lib/*-linux-*/libpsx.so.2*:
```suggestion
      /lib/*-linux-*/libcap.so.2*:
      /lib/*-linux-*/libpsx.so.2*:
```

2024-02-21 17:14 UTC, cjdcordeiro commented on slices/apt.yaml
> +      /usr/lib/dpkg/methods/apt/*:
this will also install `/usr/lib/dpkg/methods/apt/desc.apt`. Do we need that?

2024-02-21 17:14 UTC, cjdcordeiro commented on slices/apt.yaml
> +      /usr/lib/*-linux-*/libapt-private.so*:
not a binary

2024-05-30 11:14 UTC, rebornplusplus commented
Hello @lengau, hope you are doing good. Any updates on this PR?

2024-08-01 09:44 UTC, rebornplusplus commented
Hello @lengau, it has been some time since the last activity here. I see that there are some changes requested from Cris. Will you please let me know if you have some time to revisit this? Feel free to close this as well if you do not have any time. Thank you!

2024-08-22 19:12 UTC, lengau commented
Closing this as it's tragically out of date. I'll open a new one shortly.

2024-08-22 19:12 UTC, closed without merging