feat(24.04): add sed slices
canonical/chisel-releases pull request #182
Opened 2024-03-06 18:13 UTC by lwnexgen

# Proposed changes
Add simple slice for `sed` - we use it in a bunch of our entrypoints.

### Forward porting
TODO while I file them

## Testing
```bash
rm -rf fs && \
mkdir -p fs && \
~/go/bin/chisel cut --root=$(readlink -f fs) --release=$(readlink -f .) sed_bins && \
sudo chroot fs /usr/bin/sed --version
```

Should show similar output to other PRs, but I don't have a 24.04 system that will play nice with my build infrastructure to test right now.

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

2024-03-12 16:03 UTC, cjdcordeiro approved these changes
LGTM thanks!

2024-03-15 08:37 UTC, rebornplusplus requested changes

2024-03-15 08:37 UTC, rebornplusplus commented on slices/sed.yaml
> +      - libpcre2-8-0_libs
```suggestion
```

`libpcre2-8-0` comes as a dependency of `libselinux1`.

2024-03-28 08:36 UTC, rebornplusplus approved these changes
Looks good to me, thank you!

2024-03-28 08:37 UTC, merged