feat(22.04): add crun and uidmap slices
canonical/chisel-releases pull request #222
Opened 2024-04-17 13:16 UTC by endersonmaia

# Proposed changes

Add crun and uidmap slices to 22.04.

Close #221 

## Related issues/PRs

### Forward porting

- https://github.com/canonical/chisel-releases/pull/223
- https://github.com/canonical/chisel-releases/pull/224
- https://github.com/canonical/chisel-releases/pull/225

## Testing

Will 

```bash
# on a local copy in the current branch run:
mkdir rootfs
chisel cut \
    --release ./ \
    --root rootfs/ \
    --arch=amd64 \
    base-files_base \
    base-files_release-info \
    crun_bins
cat <<EOF | docker build -t crun-container . -f -
FROM scratch
COPY rootfs/ /
EOF
docker run --rm crun-container crun --version
rm -rf rootfs/
```

Expected:

```
crun version 0.17
commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
```

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context

2024-05-16 08:32 UTC, zhijie-yang requested changes
Looks good. There are some issues regarding the linting (see workflow runs) to be fixed, and it is suggested to add the copyright files explicitly in the slice definitions.

2024-05-16 09:13 UTC, linostar reviewed
slice names to sorted, and copyright need to be added:
- crum: `/usr/share/doc/crun/copyright:`
- libaudit-common: `/usr/share/doc/libaudit-common/copyright:`
- libaudit1: `/usr/share/doc/libaudit1/copyright:`
- libcap-ng0: `/usr/share/doc/libcap-ng0/copyright:`
- libcap2: `/usr/share/doc/libcap2/copyright:`
- liblz4-1: `/usr/share/doc/liblz4-1/copyright:`
- libseccomp2: `/usr/share/doc/libseccomp2/copyright:`
- libsystemd0: `/usr/share/doc/libsystemd0/copyright:`
- libyajl2: `/usr/share/doc/libyajl2/copyright:`
- uidmap: `/usr/share/doc/uidmap/copyright:`

2024-05-17 22:22 UTC, linostar approved these changes
LGTM, thanks!

2024-05-19 10:20 UTC, zhijie-yang requested changes

2024-05-19 10:20 UTC, zhijie-yang commented on slices/crun.yaml
Message from `crun` copyright file (`/usr/share/doc/crun/copyright`): Please don't forget to add me here!

2024-05-19 10:20 UTC, zhijie-yang commented on slices/uidmap.yaml
`uidmap`: So it my copyright file! It's here -> `/usr/share/doc/uidmap/copyright`!

2024-08-12 10:18 UTC, rebornplusplus reviewed
The slices look good, thanks! Only left a few comments below. 

With the recent changes around testing in the upstream branch, I think it would be nice to have a spread test for `crun` and `uidmap` as well.

2024-08-12 10:18 UTC, rebornplusplus commented on slices/crun.yaml
> +      /usr/lib/*-linux-*/libcrun.a:
This file should go in a separate `libs` slice. The slice then needs to be listed as an essential of `bins`.

2024-08-12 10:18 UTC, rebornplusplus commented on slices/libgcrypt20.yaml
> -
We don't need to change existing files blank spaces. Same for below.

2024-08-12 10:58 UTC, rebornplusplus approved these changes
Updated the trivial changes myself. Looks good to me, thank you!

Tried to add a smoke test by running `crun --version` in a `chroot` env, but `crun` runs into an error. Probably this is related: https://github.com/containers/crun/issues/1434. Reverted the commit I added for smoke test. Please feel free to add a smoke test of your own!

2024-08-19 16:41 UTC, cjdcordeiro commented
@rebornplusplus this is actually a very similar issue to #274 -> `crun` needs procfs, which doesn't exist in the chroot env and we can't create it cause the test runs inside an unprivileged container.

If we can't find a workaround until tomorrow, let's just add a `TODO` comment in the SDF and move on.

2024-08-21 12:25 UTC, cjdcordeiro commented
@endersonmaia how urgent is this? I'm trying to find a different testing strategy to support such privileged tests like yours, but it could take a few days. If you need this now, I'm happy to merge it with the simplified tests and improve those later on.

2024-08-21 12:35 UTC, endersonmaia commented
> @endersonmaia how urgent is this? I'm trying to find a different testing strategy to support such privileged tests like yours, but it could take a few days. If you need this now, I'm happy to merge it with the simplified tests and improve those later on.

I'm using my fork's branch to have this in my build pipeline, so it's not urgent.

2024-08-22 12:37 UTC, endersonmaia commented
> ... I'm trying to find a different testing strategy to support such privileged tests like yours ...

Have you considered running qemu or even firecracker?

I use the [crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_export.md) tool to generate a rootfs and together with a kernel image you could start a firecracker microVM using something like [firectl](https://github.com/firecracker-microvm/firectl)

2024-08-27 06:52 UTC, cjdcordeiro commented
Thanks @endersonmaia and thanks for the suggestions. I already have #317 up to introduce LXD as a backend for the tests execution. I've tested it with your PR and seemed to work just fine. So once it's merged, we can rebase your PR.

If you have some tests, please add them and I'll re-trigger the CI after the rebase

2024-08-28 14:32 UTC, cjdcordeiro commented
> Updated the trivial changes myself. Looks good to me, thank you!
> 
> Tried to add a smoke test by running `crun --version` in a `chroot` env, but `crun` runs into an error. Probably this is related: [containers/crun#1434](https://github.com/containers/crun/issues/1434). Reverted the commit I added for smoke test. Please feel free to add a smoke test of your own!

@rebornplusplus (or @endersonmaia ) could you please add such test here (and counterpart releases)? :pray:

2024-09-27 15:10 UTC, cjdcordeiro commented
Alright, I've added the `crun` test. Looking good. Merging.

2024-09-27 15:10 UTC, cjdcordeiro approved these changes

2024-09-27 15:11 UTC, merged