Rocks 994 ca cert mutation scripts 22.04
canonical/chisel-releases pull request #267
Opened 2024-06-24 10:24 UTC by zhijie-yang

# Proposed changes

The script `update-ca-certificates` and its corresponding config file `/etc/ca-certificates.conf` is added to the SDF of `ca-certificates`.

## Related issues/PRs
ROCKS-994

### Forward porting

#266 

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

2024-07-16 14:32 UTC, cjdcordeiro requested changes
can u pls update this according to #266

2024-07-22 07:33 UTC, cjdcordeiro approved these changes

2024-07-22 07:34 UTC, cjdcordeiro requested changes

2024-07-22 07:34 UTC, cjdcordeiro commented on slices/ca-certificates.yaml
> +      # at /etc/ssl/certs/ca-certificates.crt, the `_data-with-certs` slice should
this slice doesn't exist

2024-07-22 07:44 UTC, zhijie-yang commented on slices/ca-certificates.yaml
> +      # at /etc/ssl/certs/ca-certificates.crt, the `_data-with-certs` slice should
Fixed. Ref #285

2024-07-22 08:42 UTC, cjdcordeiro approved these changes

2024-07-22 08:52 UTC, linostar approved these changes
LGTM, Thanks!

2024-07-22 08:56 UTC, merged