Draft: feat(22.04): Slicing python3.10-venv and python3.10
canonical/chisel-releases pull request #271
Opened 2024-06-24 16:24 UTC by gregory-schiano

# Proposed changes
Adding python3.10-venv chiseled package and its dependency, including python3.10
The aim is to be able to use the python plugin on rockcraft entirely with chiseled packages, allowing very small OCI images for python applications.

## Related issues/PRs
N/A

### Forward porting
Python3.12 is available on Noble and is the default Python version for noble

## Testing
To test in a VM, start an `ubuntu-22.04`, copy this branch into `/home/chisel` folder (or mount it):
```bash
apt update && apt install -y golang-1.22 ca-certificates
update-alternatives --install /usr/bin/go go /usr/lib/go-1.22/bin/go 0
go install github.com/canonical/chisel/cmd/chisel@latest
/root/go/bin/chisel cut --release /home/chisel/ --root / python3.10-venv_ensurepip
cd ~
mkdir test
cd test
python3.10 -m venv env
echo "flask" > requirements.txt
source env/bin/activate
pip install -r requirements.txt
```

To test using rockcraft use the following `rockcraft.yaml` at the root of this repository folder
```yaml
name: python-venv
title: python-venv
version: '0.1'
summary: Testing python3.10-venv slice in bare
description: |
  Testing python3.10-venv slice in bare
base: bare
build-base: ubuntu@22.04
platforms:
  amd64:
parts:
  chisel:
    plugin: dump
    source: .
    override-build: |
      chisel cut --release ./ --root ${CRAFT_PART_INSTALL} python3.10-venv_ensurepip
  slices:
    plugin: nil
    override-build: mkdir -m 777 ${CRAFT_PART_INSTALL}/tmp
    stage-packages:
    - bash_bins
    - coreutils_bins
    - ca-certificates_data
run-user: _daemon_
```
You'll need `rockcraft` snap installed, and `docker` installed:
```bash
rockcraft pack
rockcraft.skopeo copy --insecure-policy oci-archive:python-venv_0.1_amd64.rock docker-daemon:python-venv:test
docker run --name test -d python-venv:test
docker exec -ti test bash
cd ~
mkdir test
cd test
python3.10 -m venv env
echo "flask" > requirements.txt
source env/bin/activate
pip install -r requirements.txt
```

## Checklist
* [X] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [X] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context
This a followup PR of https://github.com/canonical/chisel-releases/pull/259 as Python3.11 is a `universe` package, running a release candidate of Python3.11. We wanted to have a sliced Python version relying on a maintained package.

2024-06-24 17:08 UTC, cjdcordeiro requested changes

2024-06-24 17:08 UTC, cjdcordeiro commented on slices/libpython3.10-stdlib.yaml
You're missing:
 - `/usr/lib/python3.10/lib-dynload/_testclinic.cpython-310-x86_64-linux-gnu.so`

2024-06-24 17:08 UTC, cjdcordeiro commented on slices/python3.10-minimal.yaml
> +      # The next two directories are created to mimic the behaviour in
nice

2024-06-24 19:26 UTC, gregory-schiano commented on slices/libpython3.10-stdlib.yaml
The file wasn't referenced here: https://packages.ubuntu.com/jammy/amd64/libpython3.10-stdlib/filelist
But seems to be in the package, fixing it in the next commit

2024-06-24 19:42 UTC, javierdelapuente approved these changes

2024-06-25 06:15 UTC, cjdcordeiro approved these changes

2024-06-25 06:15 UTC, merged