feat(24.04): add libcrack-runtime and its dependencies
canonical/chisel-releases pull request #329
Opened 2024-09-03 07:57 UTC by Meulengracht

# Proposed changes

Proposing libcrack-runtime and the dependencies it has. Unfortunately I was not able to write a mutation script that does what `update-cracklib` does due to limitations in how we write files. We need the capability to write raw file bytes instead of formatted as text, as it otherwise results in malaligned files.

### Forward porting

I can propose this for 24.10 when this is approved

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context

My attempt at the mutation script: https://paste.ubuntu.com/p/Jc5vvgk3tN/

2024-09-11 12:38 UTC, clay-lake requested changes

2024-09-11 12:38 UTC, clay-lake commented on slices/libmagic-mgc.yaml
> +  config:
Can we call this slice `data` since these files are binary not easily edited?

2024-09-11 12:38 UTC, rebornplusplus requested changes
Nice changes! I left a few comments below.

In addition to the changes, could you please add a spread test for `file` as well? Just a smoke test will do. :)

2024-09-11 12:38 UTC, rebornplusplus commented on slices/cracklib-runtime.yaml
> +# https://paste.ubuntu.com/p/Jc5vvgk3tN/
Nice work there! It's a shame we cannot raw bytes yet.
On another note, could this link expire some day? If so, I would want there to be something that does not expire, Github Gist maybe?

2024-09-11 12:38 UTC, rebornplusplus commented on tests/spread/integration/cracklib-runtime/task.yaml
> +  - -ubuntu-24.04-s390x
Curious to know why you don't need these.

2024-10-31 10:29 UTC, linostar requested changes

2024-10-31 10:29 UTC, linostar commented on tests/spread/integration/cracklib-runtime/task.yaml
> +  fi
Can you also add smoke tests for the rest of the binaries in cracklib-runtime_bins slice?

2025-08-13 11:30 UTC, closed without merging