slices: add gzip and tar
canonical/chisel-releases pull request #331
Opened 2024-09-03 08:49 UTC by Meulengracht

# Proposed changes

Propose tools gzip and tar. I did not propose tar alone, as tar invokes gzip as the underlying compression tool. Thus there is no dedicated test for gzip as the tar test is essentially using gzip.

### Forward porting

I can propose this for 24.10 if its approved

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

2024-09-09 14:47 UTC, clay-lake commented on slices/tar.yaml
> +package: tar
FYI: there is another tar slice on its way. https://github.com/canonical/chisel-releases/pull/320/files#diff-d2ba6fca2d17b4a0cebd482195bfd53d541b151be0ad2fd14496adf5e6537685

2024-09-30 12:36 UTC, cjdcordeiro reviewed
@Meulengracht can you pls rebase :)

2024-10-02 10:12 UTC, cjdcordeiro requested changes
(some additional tests needed - discussed offline)

2024-10-31 11:10 UTC, linostar reviewed
Other than the missing tests, this looks good to me.

2025-01-27 14:37 UTC, rebornplusplus approved these changes
This looks good to me. Thank you!

2025-02-05 09:37 UTC, zhijie-yang requested changes
There are still many binaries not tested. Besides, we should remove the `systems:` directive in the yaml, since ppc64le and s390x are not tested by `spread` anyways.

2025-02-05 09:37 UTC, zhijie-yang commented on tests/spread/integration/gzip/task.yaml
> +
```suggestion
```

2025-02-18 13:53 UTC, cjdcordeiro commented
Hi @norrisjeremy 

this PR was bringing that in but it hasn't been updated in a while. 
Checking on its status with @Meulengracht ?

2025-02-18 14:16 UTC, norrisjeremy commented
> Hi @norrisjeremy
> 
> this PR was bringing that in but it hasn't been updated in a while. Checking on its status with @Meulengracht ?

Hi @cjdcordeiro,

Yes, we would very much like to see an SDF landed for `gzip` since it is a commonly used utility.
If you want, I can see if we can redo this as a fresh PR, since @Meulengracht seems to have gone radio silent.

2025-02-18 14:28 UTC, cjdcordeiro commented
> > Hi @norrisjeremy
> > this PR was bringing that in but it hasn't been updated in a while. Checking on its status with @Meulengracht ?
> 
> Hi @cjdcordeiro,
> 
> Yes, we would very much like to see an SDF landed for `gzip` since it is a commonly used utility. If you want, I can see if we can redo this as a fresh PR, since @Meulengracht seems to have gone radio silent.

That would be very welcome :rocket:

2025-08-13 10:58 UTC, closed without merging