feat(24.04): add debianutils
canonical/chisel-releases pull request #335
Opened 2024-09-04 07:21 UTC by Meulengracht

# Proposed changes

Add debianutils

## Related issues/PRs

### Forward porting

Can open for 24.10 if approved

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

2024-09-09 14:29 UTC, clay-lake requested changes

2024-09-09 14:29 UTC, clay-lake commented on slices/debianutils.yaml
> +      /usr/bin/savelog:
A few of these executables are scripts. We need to figure out how we are going to link /bin/sh in #337 first

2024-10-31 10:57 UTC, linostar requested changes

2024-10-31 10:57 UTC, linostar commented on slices/debianutils.yaml
> +      - libc6_libs
`dash_bins` can be added as a dependency here for the executables that are actually shell scripts.

2024-10-31 10:57 UTC, linostar commented on slices/debianutils.yaml
> +      /usr/bin/which: {symlink: /usr/bin/which.debianutils}
`/usr/bin/which.debianutils:` should be in `contents` here so that this slice doesn't unnecessarily depend on unneeded binaries in bins slice.

2024-10-31 10:57 UTC, linostar commented on slices/debianutils.yaml
> +      /usr/share/debianutils/shells:
This file isn't necessary as a slice. However, this file is copied in the maintainer scripts to `/etc/shells` if that file doesn't exist, so please add a mutation script for that.

2024-10-31 10:57 UTC, linostar commented on tests/spread/integration/debianutils/task.yaml
> +  # will output an error due to missing dpkg-realpath
Since it's this case, the package `dpkg` which contains dpkg-realpath should be a dependency of debianutils as well.

2025-08-15 16:21 UTC, lengau requested changes
The open comments here are still relevant.

2026-02-19 23:59 UTC, lczyk commented
closing since 1) decayed and 2) we already have `debianutils` partially sliced in 24.04

2026-02-19 23:59 UTC, closed without merging