feat: openjdk-17 slices
canonical/chisel-releases pull request #350
Opened 2024-09-18 05:02 UTC by vpa1977

# Proposed changes

Add openjdk-17 slices except AWT slice as it needs harfbuzz to be merged.

## Related issues/PRs

[harfbuzz](https://github.com/canonical/chisel-releases/pull/348)

### Forward porting

## Checklist

* [ ] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [ ] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [ ] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context

2024-09-23 11:01 UTC, rebornplusplus reviewed
Looks good in general. Just a few questions and suggestions below.

2024-09-23 11:01 UTC, rebornplusplus commented on slices/openjdk-17-jre-headless.yaml
> +slices:
We should probably leave a one-liner comment on top of each slice describing what it does.

2024-09-23 23:34 UTC, vpa1977 commented on tests/spread/integration/openjdk-17-jre-headless/task.yaml
> +      classescache)
Fixed, added back classescache slice.

2024-09-23 23:38 UTC, vpa1977 commented on slices/openjdk-17-jre-headless.yaml
> +      - openjdk-17-jre-headless_security
We may want to add debug/monitoring capabilities - default spring boot application requires them.

2024-09-23 23:43 UTC, vpa1977 commented on slices/openjdk-17-jre-headless.yaml
> +package: openjdk-17-jre-headless
`/usr/lib/jvm/java-17-openjdk-amd64/lib/classlist                                                 openjdk-17-jre-headless` belong to classescache slice, .jsa files are generated with `java -Xdump`

`/usr/lib/jvm/java-17-openjdk-amd64/lib/libjsvml.so                                               openjdk-17-jre-headless` - incubating feature, vector API, omitted
`/usr/lib/jvm/java-17-openjdk-amd64/lib/libsyslookup.so                                           openjdk-17-jre-headless` -  incubating feature, Foreign Function API, omitted. 

Rest are awt slice which is not included in the MR.

2024-09-24 01:54 UTC, vpa1977 commented
Needs  pipeline retry  - spread failing with "cannot fetch from archive"

2024-09-24 06:57 UTC, rebornplusplus approved these changes
Looks good to me, thank you!

I have re-triggered the failing pipeline. It's passing now.

2024-09-30 13:17 UTC, cjdcordeiro requested changes
again the same comments as in https://github.com/canonical/chisel-releases/pull/313 and #349

2024-10-08 20:21 UTC, vpa1977 commented
Note: dropped jvm.cfg-default https://github.com/canonical/chisel-releases/pull/363

2024-10-18 04:02 UTC, rebornplusplus approved these changes
Looks great, thank you very much!

2024-10-18 06:17 UTC, cjdcordeiro approved these changes

2024-10-18 06:18 UTC, merged