Rework of PR #49 "[22.04] Add slices for publicsuffix and libproxy1v5"
canonical/chisel-releases pull request #389
Opened 2024-11-18 15:30 UTC by clay-lake

Rework of #49, as it has not been updated in a while.

This PD adds the following changes:
- The data slice in `publicsuffix` is more explicit following earlier comments in #49 
- `glib-networking` and dependent `gsettings-desktop-schemas` were removed. Since these packages related to the gnome desktop environment, I am hesitant to add them unless they can be tested in a minimal rootfs. 

## Port Forwards
See #461 and #462

2024-11-18 15:35 UTC, rebornplusplus approved these changes
Looks good to me, thank you!

2025-01-16 13:51 UTC, zhijie-yang approved these changes
LGTM, thanks!

2025-01-16 13:57 UTC, rebornplusplus commented
@cjdcordeiro this is OK to merge.

2025-01-16 18:05 UTC, cjdcordeiro approved these changes
thanks

2025-01-16 18:07 UTC, cjdcordeiro requested changes
oops spoke too soon. we're missing the forward ports for these

2025-01-21 14:50 UTC, clay-lake commented
> oops spoke too soon. we're missing the forward ports for these

Thanks! I forwarded these changes on to 24.04 (#461 ) and 24.10 (#462 ).

2025-01-21 14:51 UTC, rebornplusplus commented
@jnsgruk will you please take a look at this one? I believe the port forward requirements are met.

2025-01-21 14:54 UTC, merged