feat(24.10): add .NET9 slices
canonical/chisel-releases pull request #436
Opened 2024-12-16 14:28 UTC by zhijie-yang

# Proposed changes

This PR add the slice definitions for .NET9 packages. 

* For the current `chisel` implementation, conflicts with .NET8 packages are expected.
* The spread tests are yet to be added.

### Forward porting

Not applicable.

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

2024-12-18 13:23 UTC, cjdcordeiro approved these changes
Thanks for this. And for the new tests ! LGTM

2024-12-20 10:52 UTC, clay-lake requested changes
Few quick fixes, otherwise looks good!

2024-12-20 10:52 UTC, clay-lake commented on tests/spread/integration/aspnetcore-runtime-9.0/task.yaml
> +  sleep 5
I would wait for the port to open like we do here. Worst this fails due to race condition, best case we speed up the test.
Here is an example with fuser you can paste in.
https://github.com/canonical/chisel-releases/blob/ubuntu-24.10/tests/spread/integration/git/task.yaml#L98

2024-12-20 10:52 UTC, clay-lake commented on tests/spread/integration/aspnetcore-runtime-9.0/task.yaml
> +  # smoking test the .NET runtime
We can remove this test since we already run it in `tests/spread/integration/dotnet-host-9.0/task.yaml`.

2024-12-20 10:52 UTC, clay-lake commented on tests/spread/integration/dotnet-runtime-9.0/task.yaml
> +  chroot "${rootfs}" /usr/bin/dotnet --info
We can remove this. See `tests/spread/integration/aspnetcore-runtime-9.0/task.yaml`

2024-12-20 13:17 UTC, clay-lake approved these changes
LGTM. Thanks! :snowman_with_snow:

2024-12-20 14:01 UTC, merged