feat(24.10): Add SDF for `libavcodec61` and dependencies
canonical/chisel-releases pull request #442
Opened 2024-12-25 20:37 UTC by HadrienPatte

# Proposed changes

Add SDF for `libavcodec61` and dependencies

## Related issues/PRs

24.04 PR: #441

### Forward porting

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context

2024-12-25 20:46 UTC, HadrienPatte commented on slices/libavutil59.yaml
> +      - ocl-icd-libopencl1_libs
See https://github.com/canonical/chisel-releases/pull/441#discussion_r1897472587

2025-01-06 10:49 UTC, cjdcordeiro commented on slices/libavcodec61.yaml
> +      # The librav1e0.7_libs dependency is currently ommited, it can be added again
thanks for these comments.

2025-01-06 10:53 UTC, cjdcordeiro requested changes
Thanks for this! 

It's looking good. I think we could just use a couple of tests.

2025-01-06 10:53 UTC, cjdcordeiro commented on slices/libgdk-pixbuf-2.0-0.yaml
> +      /usr/lib/*-linux-*/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders:
can you please add a test for this binary?

2025-01-06 10:53 UTC, cjdcordeiro commented on slices/shared-mime-info.yaml
> +      /usr/bin/update-mime-database:
can we also have a test for this pls?

2025-01-06 20:36 UTC, HadrienPatte commented on slices/libgdk-pixbuf-2.0-0.yaml
> +      /usr/lib/*-linux-*/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders:
Thanks for catching that, ported the tests from [24.04](https://github.com/lengau/chisel-releases/blob/1947fcf209051e5eaaeccbe2efd7b7af33386de8/tests/spread/integration/libgdk-pixbuf-2.0-0/task.yaml) in 6fc738e

2025-01-06 20:36 UTC, HadrienPatte commented on slices/shared-mime-info.yaml
> +      /usr/bin/update-mime-database:
Thanks for catching that, ported the tests from [24.04](https://github.com/lengau/chisel-releases/blob/1947fcf209051e5eaaeccbe2efd7b7af33386de8/tests/spread/integration/shared-mime-info/task.yaml) in 6fc738e

2025-01-07 07:31 UTC, cjdcordeiro approved these changes
Thanks for adding the missing tests. LGTM ;)

2025-01-21 08:31 UTC, rebornplusplus approved these changes
Looks good to me, thanks!

2025-01-21 08:32 UTC, merged