feat(24.04): add slices for Gearman and dependencies
canonical/chisel-releases pull request #443
Opened 2024-12-30 17:19 UTC by eunufe

# Proposed changes

feat(24.04): add slices for Gearman and dependencies

## Related issues/PRs

### Forward porting

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context

2025-01-06 11:24 UTC, cjdcordeiro approved these changes
Very tidy! Thanks for the contribution. It LGTM.

2025-01-06 11:25 UTC, cjdcordeiro requested changes
Ah, we might just need a fix on the linting (see the CI checks).

As for the CLA, please let me know if you've signed it, cause if so, it might need some manual action on our side.

2025-01-06 12:47 UTC, norrisjeremy commented
> Ah, we might just need a fix on the linting (see the CI checks).
> 
> As for the CLA, please let me know if you've signed it, cause if so, it might need some manual action on our side.

@eunufe Can you review and clean-up the trailing whitespace characters the linter detected? I missed them in our internal review of this.

2025-01-06 13:57 UTC, cjdcordeiro commented
> > Ah, we might just need a fix on the linting (see the CI checks).
> > As for the CLA, please let me know if you've signed it, cause if so, it might need some manual action on our side.
> 
> @cjdcordeiro Eloho signed the CLA several weeks ago, so I think some sort of manual action is required for you database.

Yep I saw your message in #444 and have already reached out to my colleagues to get it sorted out. Once I hear back from them I'll re-run the check ;)

2025-01-06 14:03 UTC, norrisjeremy commented
> > > Ah, we might just need a fix on the linting (see the CI checks).
> > > As for the CLA, please let me know if you've signed it, cause if so, it might need some manual action on our side.
> > 
> > 
> > @cjdcordeiro Eloho signed the CLA several weeks ago, so I think some sort of manual action is required for you database.
> 
> Yep I saw your message in #444 and have already reached out to my colleagues to get it sorted out. Once I hear back from them I'll re-run the check ;)

Great, thanks!

2025-01-06 16:13 UTC, norrisjeremy commented
> > Ah, we might just need a fix on the linting (see the CI checks).
> > As for the CLA, please let me know if you've signed it, cause if so, it might need some manual action on our side.
> 
> @eunufe Can you review and clean-up the trailing whitespace characters the linter detected? I missed them in our internal review of this.

@cjdcordeiro Something appears to not be working correctly the YAML linter action.
Eloho pushed a change to fix the trailing whitespace, but now it appears to be issuing warnings for other unrelated SDFs?

2025-01-06 16:15 UTC, norrisjeremy commented
> > > Ah, we might just need a fix on the linting (see the CI checks).
> > > As for the CLA, please let me know if you've signed it, cause if so, it might need some manual action on our side.
> > 
> > 
> > @eunufe Can you review and clean-up the trailing whitespace characters the linter detected? I missed them in our internal review of this.
> 
> @cjdcordeiro Something appears to not be working correctly the YAML linter action. Eloho pushed a change to fix the trailing whitespace, but now it appears to be issuing warnings for other unrelated SDFs?

Oops, disregard.
The issue was buried in the avalanche of warnings that the linter output for all the existing SDFs.

2025-01-06 16:39 UTC, cjdcordeiro approved these changes
Thanks for the updates. The CLA is also passing now ;)

2025-01-16 13:47 UTC, rebornplusplus reviewed
The slices are quite nice, thank you very much!

I just have a couple of comments below. Let me know what you think about those.

2025-01-16 13:47 UTC, rebornplusplus commented on tests/spread/integration/gearman-job-server/task.yaml
> +  chroot "${rootfs}/" gearmand -h
I wonder if there's a practical usage we could test here instead of help. If so, and if it's easy and convenient, let's please test that.

2025-01-16 13:47 UTC, rebornplusplus commented on tests/spread/integration/gearman-tools/task.yaml
> +  chroot "${rootfs}/" gearman -H
Same comment as above.

2025-01-16 14:35 UTC, rebornplusplus commented on tests/spread/integration/gearman-job-server/task.yaml
> +  chroot "${rootfs}/" gearmand -h
Ah okay, this is fine if that's not simple enough.

2025-01-16 14:35 UTC, rebornplusplus commented on tests/spread/integration/gearman-tools/task.yaml
> +  chroot "${rootfs}/" gearman -H
https://github.com/canonical/chisel-releases/pull/443#discussion_r1918672814

2025-01-16 14:36 UTC, merged