feat(24.10): add slices for Gearman and dependencies
canonical/chisel-releases pull request #444
Opened 2024-12-30 17:28 UTC by eunufe

# Proposed changes

feat(24.10): add slices for Gearman and dependencies

## Related issues/PRs

#443 

### Forward porting

## Checklist

* [x] I have read the [contributing guidelines](
https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md)
* [x] I have tested my changes ([see how](https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md#7-test-your-slices-before-opening-a-pr))
* [x] I have already submitted the [CLA form](
https://ubuntu.com/legal/contributors/agreement)

## Additional Context

2025-01-06 11:27 UTC, cjdcordeiro requested changes
Thanks :) 

We just need the linting fixes for https://github.com/canonical/chisel-releases/pull/444/files#diff-25438d83930474416365b0933b7fd9f4f2565d4d1381c878338bcfa181be5110

2025-01-06 12:47 UTC, norrisjeremy commented
> Thanks :)
> 
> We just need the linting fixes for https://github.com/canonical/chisel-releases/pull/444/files#diff-25438d83930474416365b0933b7fd9f4f2565d4d1381c878338bcfa181be5110

@eunufe Can you review and clean-up the trailing whitespace characters the linter detected? I missed them in our internal review of this.

2025-01-06 16:39 UTC, cjdcordeiro approved these changes
thanks for the changes ;)

2025-01-17 09:37 UTC, zhijie-yang approved these changes
Looks good to me. Thanks.

This should be ready for the merge @cjdcordeiro

2025-01-17 14:23 UTC, merged