[22.04] Add slices for libgnutls, libsoup and glib-networking
canonical/chisel-releases pull request #49
Opened 2023-08-08 12:30 UTC by ozanmakes

This PR adds various networking libraries and their dependencies.

2023-08-18 13:29 UTC, cjdcordeiro requested changes
Thanks for the contribution @osener . This is a very welcome addition :)

Although functional, I've left a few requests that relate to the design of slices. The overall message is that we should be as conservative as possible when it comes to the use of globs. With these changes, it should be ready to be merged.

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/gsettings-desktop-schemas.yaml
> +      /usr/share/glib-2.0/schemas/*:
same here. I believe this whole slice should be called `config`. `data` is more appropriate for something like `ca-certificates` which delivers data files like `/etc/ssl/certs/ca-certificates.crt`.

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/gsettings-desktop-schemas.yaml
> +      /usr/share/glib-2.0/schemas/*:
```suggestion
      /usr/share/glib-2.0/schemas/10_gsettings-desktop-schemas.gschema.override:
      /usr/share/glib-2.0/schemas/org.gnome.desktop.*.gschema.xml:
      /usr/share/glib-2.0/schemas/org.gnome.desktop.enums.xml:
      /usr/share/glib-2.0/schemas/org.gnome.system.*.gschema.xml:      
```

(I think this should work, but please double check :) )

So, like in previous comments, I prefer to encourage a conservative use of globs. Although they can make slices much smaller, at scale, they can also become a burden and hard to trace if they are too generic. Whenever possible, I'd try to find a sweet spot between simplicity, maintainability and explicitness. In this example, I've sacrificed 3 lines of the slice, but not only it makes the slice easier to read, but it also saves us from potential collisions with other packages in the future.

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/libgnutls30.yaml
> +
```suggestion
```

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/libsoup2.4-1.yaml
> +    essential:
I think you're missing a dependency to `glib-networking_libs`

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/libsoup2.4-1.yaml
> +    essential:
also for `libsoup2.4-common` and `libxml2` (you can skip the former though as it doesn't bring any libraries)

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/libsoup2.4-1.yaml
> +      - libicu70_libs
I don't think this is a dependency
```suggestion
```

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/libsoup2.4-1.yaml
> +      - liblzma5_libs
same here
```suggestion
```

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/libsoup2.4-1.yaml
> +      /usr/lib/*-linux-*/libsoup-2.4.so.*:
```suggestion
      /usr/lib/*-linux-*/libsoup-2.4.so.1*:
```

2023-08-18 13:29 UTC, cjdcordeiro commented on slices/publicsuffix.yaml
> +      /usr/share/publicsuffix/*:
this path seems to be specific to this pkg, so the glob is a bit safer to use here. Nonetheless, given that there are only 3 files within, it is safer to just list them explicitly :)

2024-08-01 10:27 UTC, rebornplusplus commented
Hi @ozanmakes, it has been some time since the last activity here. The PR could use a rebase/merge since there are some conflicts already. There are some changes requested as well. Will you please let me know if you have some time to go over the comments and update the PR? Thank you!

2024-09-26 17:05 UTC, cjdcordeiro commented on slices/gsettings-desktop-schemas.yaml
> +      /usr/share/glib-2.0/schemas/*:
these are all ascii files, so let's keep data as a catch all

2024-10-23 08:30 UTC, clay-lake commented
Hi Everyone, this PR has been quite for a while. I'd like to keep some of these changes, so I made a reworked PR here #379. If the rework is merged I will close this PR.

2024-11-18 10:56 UTC, cjdcordeiro commented
> Hi everyone, this PR has been quite for a while. I'd like to keep some of these changes, so I made a reworked PR here #379. If the rework is merged I will close this PR.

Thanks and ACK!

2025-01-27 14:24 UTC, rebornplusplus commented
Closed by #389.

2025-01-27 14:24 UTC, closed without merging