Adding slices for libldap-2.5 and dependencies
canonical/chisel-releases pull request #55
Opened 2023-08-24 14:01 UTC by nhart12

Adds slices for ldap and dependencies. Includes symlink to fix issues with most downstream dotnet runtime dependent packages

2023-08-24 15:27 UTC, cjdcordeiro requested changes
this is great! thanks @nhart12 

I'll try to review it before EOW, but in the meantime (since we don't yet have any automated linters) could you please ensure your files are indented with 2 spaces? Can you please also add a new line at the end of each file?

Thanks :pray:

2023-08-24 16:01 UTC, woky reviewed
Don't like the library symlink. Otherwise, LGTM.

2023-08-24 16:10 UTC, nhart12 commented on slices/libldap-2.5-0.yaml
> +        { symlink: /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0 }
agreed, had that in there for my local build and forgot to remove it for this PR

2023-08-24 16:10 UTC, nhart12 commented on slices/libldap-2.5-0.yaml
> +        { symlink: /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0 }
removed

2023-08-24 16:49 UTC, woky approved these changes

2023-08-25 08:42 UTC, cjdcordeiro requested changes
Thanks for the updates!

I'm suggesting a few changes to make the globs a but more restrictive in order to avoid future conflicts, but after that, it LGTM ;)

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libgmp10.yaml
> +      /usr/lib/*-linux-*/libgmp.so.*:
```suggestion
      /usr/lib/*-linux-*/libgmp.so.10*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libgnutls30.yaml
> +      /usr/lib/*-linux-*/libgnutls*.so.*:
```suggestion
      /usr/lib/*-linux-*/libgnutls*.so.30*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libhogweed6.yaml
> +      /usr/lib/*-linux-*/libhogweed.so*:
```suggestion
      /usr/lib/*-linux-*/libhogweed.so.6*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libidn2-0.yaml
> +      /usr/lib/*-linux-*/libidn2.so*:
```suggestion
      /usr/lib/*-linux-*/libidn2.so.0*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libldap-2.5-0.yaml
> +      /usr/lib/*-linux-*/liblber-2.5.so.*:
```suggestion
      /usr/lib/*-linux-*/libldap-2.5.so.0*:
      /usr/lib/*-linux-*/liblber-2.5.so.0*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libnettle8.yaml
> +      /usr/lib/*-linux-*/libnettle.so*:
```suggestion
      /usr/lib/*-linux-*/libnettle.so.8*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libp11-kit0.yaml
> +      /usr/lib/*-linux-*/libp11-kit.so.*:
```suggestion
      /usr/lib/*-linux-*/libp11-kit.so.0*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libsasl2-2.yaml
> +      /usr/lib/*-linux-*/libsasl*.so.*:
```suggestion
      /usr/lib/*-linux-*/libsasl*.so.2*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libsasl2-modules-db.yaml
> +      /usr/lib/*-linux-*/sasl2/*:
```suggestion
      /usr/lib/*-linux-*/sasl2/libsasldb.so*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libtasn1-6.yaml
> +      /usr/lib/*-linux-*/libtasn*.so.*:
```suggestion
      /usr/lib/*-linux-*/libtasn1.so.6*:
```

2023-08-25 08:42 UTC, cjdcordeiro commented on slices/libunistring2.yaml
> +      /usr/lib/*-linux-*/libunistring.so*:
```suggestion
      /usr/lib/*-linux-*/libunistring.so.2*:
```

2023-08-25 14:37 UTC, cjdcordeiro requested changes
thanks, but you've forgotten this: https://github.com/canonical/chisel-releases/pull/55#discussion_r1305373916

For future reference, it is easier to simply accept/commit the suggestions as that will create a nicer tracing story in GH. With the force push, I had to compare the suggestions manually, which is very error-prone.

2023-08-25 15:10 UTC, nhart12 commented
> thanks, but you've forgotten this: [#55 (comment)](https://github.com/canonical/chisel-releases/pull/55#discussion_r1305373916)
> 
> For future reference, it is easier to simply accept/commit the suggestions as that will create a nicer tracing story in GH. With the force push, I had to compare the suggestions manually, which is very error-prone.

yeah I noticed that after the fact, sorry about that

2023-08-25 15:21 UTC, merged

2023-08-25 15:22 UTC, nhart12 commented
Thank you. Just for reference I noticed this has a lot of the same libs as defined here so may need a rebase
https://github.com/canonical/chisel-releases/pull/49