feat: add python3.11 and dependencies
canonical/chisel-releases pull request #68
Opened 2023-11-07 10:34 UTC by hartmutobendorf

Added python3.11 and its dependencies for 22.04.

Removed file patterns that were no longer used for libpython.

2023-11-10 12:52 UTC, rebornplusplus requested changes
Hi! Nice chiselling there. It's looking good.

I left a few comments below after a quick scan through the files. I will be thorough in the next pass. Here are a few general comments which I think might improve this PR:

* I think it is better to sort the entries in `essential` and `contents` in the slice definition files. I agree it hasn't been done so for the existing files in the repo. But I think it would be nice to do that from now on.
* nit: There are no newlines at the end of most files.

2023-11-10 12:52 UTC, rebornplusplus commented on slices/libpython3.11-minimal.yaml
> +      /usr/lib/python3.11/types.py:
`/usr/lib/python3.11/typing.py` file seems to be missing.

2023-11-10 12:52 UTC, rebornplusplus commented on slices/libpython3.11-minimal.yaml
> +      /usr/lib/python3.11/enum.py:
`/usr/lib/python3.11/filecmp.py` seems to be missing.

2023-11-10 12:52 UTC, rebornplusplus commented on slices/libpython3.11-stdlib.yaml
I think some new libraries in Python3.11 are not included in this file.

To help you out, here's a diff of the paths between [libpython3.8-stdlib](https://packages.ubuntu.com/focal/amd64/libpython3.8-stdlib/filelist) and [libpython3.11-stdlib](https://packages.ubuntu.com/jammy-updates/amd64/libpython3.11-stdlib/filelist):

```diff
1c1,5
< /usr/lib/python3.8/__phello__.foo.py
---
> /usr/lib/python3.11/__hello__.py
> /usr/lib/python3.11/__phello__/__init__.py
> /usr/lib/python3.11/__phello__/spam.py
> /usr/lib/python3.11/_aix_support.py
> /usr/lib/python3.11/_bootsubprocess.py
3c7
< /usr/lib/python3.8/_dummy_thread.py
---
> /usr/lib/python3.11/_distutils_system_mod.py
25a30
> /usr/lib/python3.11/asyncio/mixins.py
34a40
> /usr/lib/python3.11/asyncio/taskgroups.py
35a42,43
> /usr/lib/python3.11/asyncio/threads.py
> /usr/lib/python3.11/asyncio/timeouts.py
43d50
< /usr/lib/python3.8/binhex.py
80,81d86
< /usr/lib/python3.8/dummy_threading.py
< /usr/lib/python3.8/filecmp.py
83d87
< /usr/lib/python3.8/formatter.py
87a92
> /usr/lib/python3.11/graphlib.py
133a139
> /usr/lib/python3.11/lib-dynload/_typing.cpython-311-x86_64-linux-gnu.so
136a143
> /usr/lib/python3.11/lib-dynload/_zoneinfo.cpython-311-x86_64-linux-gnu.so
141d147
< /usr/lib/python3.8/lib-dynload/parser.cpython-311-x86_64-linux-gnu.so
145a152
> /usr/lib/python3.11/lib-dynload/xxlimited_35.cpython-311-x86_64-linux-gnu.so
209d215
< /usr/lib/python3.8/symbol.py
231a238,243
> /usr/lib/python3.11/test/support/bytecode_helper.py
> /usr/lib/python3.11/test/support/hashlib_helper.py
> /usr/lib/python3.11/test/support/import_helper.py
> /usr/lib/python3.11/test/support/interpreters.py
> /usr/lib/python3.11/test/support/logging_helper.py
> /usr/lib/python3.11/test/support/os_helper.py
232a245
> /usr/lib/python3.11/test/support/socket_helper.py
233a247,248
> /usr/lib/python3.11/test/support/threading_helper.py
> /usr/lib/python3.11/test/support/warnings_helper.py
236a252,255
> /usr/lib/python3.11/tomllib/__init__.py
> /usr/lib/python3.11/tomllib/_parser.py
> /usr/lib/python3.11/tomllib/_re.py
> /usr/lib/python3.11/tomllib/_types.py
240d258
< /usr/lib/python3.8/typing.py
242a261
> /usr/lib/python3.11/unittest/_log.py
265a285
> /usr/lib/python3.11/wsgiref/types.py
294a315,318
> /usr/lib/python3.11/zoneinfo/__init__.py
> /usr/lib/python3.11/zoneinfo/_common.py
> /usr/lib/python3.11/zoneinfo/_tzpath.py
> /usr/lib/python3.11/zoneinfo/_zoneinfo.py
```

But there does not seem to be adequate diff in the slice definition file (from 3.8) to accommodate the new libraries.

```diff
18c18
<       - mime-support_mime-types
---
>       - media-types_data
42d41
<       /usr/lib/python3.8/typing.py:
51c50
<       - libffi7_libs
---
>       - libffi8_libs
69d67
<       /usr/lib/python3.8/_dummy_thread.py:
71d68
<       /usr/lib/python3.8/dummy_threading.py:
141c138
<       /usr/lib/python3.8/__phello__.foo.py:
---
>       /usr/lib/python3.11/__phello__/**:
183c180
<       /usr/lib/python3.8/filecmp.py:
---
> #      /usr/lib/python3.11/filecmp.py:
256d252
<       /usr/lib/python3.8/lib-dynload/parser.cpython-311-*-linux-*.so:
259d254
<       /usr/lib/python3.8/symbol.py:
295d289
<       /usr/lib/python3.8/binhex.py:
306d299
<       - libmpdec2_libs
382,383c375
<       /usr/lib/python3.8/formatter.py:
<       /usr/lib/python3.8/this.py:
---
>       /usr/lib/python3.11/this.py:
\ No newline at end of file
```

2023-11-28 15:59 UTC, cjdcordeiro requested changes
There are indeed some files missing. I'll confirm and defer to @rebornplusplus comments on that.

@hartmutobendorf we'd love to have your contribution merged :) do you think you'll be able to address the change requests? If not, we might take over the PR sometime during the next couple of weeks. Please let us know ;)

2023-11-28 15:59 UTC, cjdcordeiro commented on slices/python3.11-minimal.yaml
> +      - libc6_libs
why is libc6 a dependency here? It is already a dependency of libexpat1 and zlib1g, so this is redundant

2023-11-28 15:59 UTC, cjdcordeiro commented on slices/readline-common.yaml
> +      /etc/inputrc: { copy: /usr/share/readline/inputrc }
```suggestion
      /etc/inputrc: { copy: /usr/share/readline/inputrc }

```

2023-11-28 15:59 UTC, cjdcordeiro commented on slices/libreadline8.yaml
> +      /lib/*-linux-*/libhistory.so.8*:
```suggestion
      /lib/*-linux-*/libhistory.so.8*:

```

2023-11-28 15:59 UTC, cjdcordeiro commented on slices/libpython3.11-stdlib.yaml
> +      /usr/lib/python3.11/this.py:
```suggestion
      /usr/lib/python3.11/this.py:

```

2023-11-28 15:59 UTC, cjdcordeiro commented on slices/libpython3.11-minimal.yaml
> +      /usr/lib/python3.11/zipimport.py:
```suggestion
      /usr/lib/python3.11/zipimport.py:

```

2023-12-15 06:06 UTC, rebornplusplus commented
Hello @hartmutobendorf. Since we have not heard from you in a while, I have opened a new PR for Python3.11 slices: https://github.com/canonical/chisel-releases/pull/82. Thanks for starting this off, your work helped a lot for the new PR. I will be closing this PR, but please feel free to review the other one. I have added you as an optional reviewer.

2023-12-15 06:06 UTC, closed without merging