feat(24.04): add tzdata slices
canonical/chisel-releases pull request #92
Opened 2024-01-04 09:03 UTC by rebornplusplus

This PR adds the tzdata slices for 24.04.

---

:yellow_circle: Changes are same in #91.

2024-01-08 15:48 UTC, cjdcordeiro requested changes
Thanks for this. What about `/usr/share/zoneinfo/zonenow.tab`?

2024-01-09 07:16 UTC, rebornplusplus commented
> Thanks for this. What about `/usr/share/zoneinfo/zonenow.tab`?

Nice catch, thank you! Missed that one, sorry. It's added now. Please take another look.

2024-01-09 07:34 UTC, cjdcordeiro approved these changes
ty LGTM

2024-01-09 07:56 UTC, linostar approved these changes

2024-01-09 07:58 UTC, merged